#!/bin/sh -e

package="$__object_id"
user="$(cat "$__object/parameter/user")"
directory="$(cat "$__object/parameter/directory")/$package"

#install dependencies as root
echo "grep makedepends $directory/PKGBUILD > $directory/deps;"
echo "source $directory/deps;"
echo 'if [[ !(${#makedepends[@]} -eq 0) ]]; then pacman -Sy --noconfirm --needed --asdeps "${makedepends[@]}"; else echo "no make dependencies"; fi;'

#make package as user
echo "su - $user -s /bin/bash -c \"(cd $directory && makepkg -f)\";"

#install package as root
echo "pacman --noconfirm -U $directory/*-x86_64.pkg.*;"
