#!/bin/sh -e

package="$__object_id"
user="$(cat "$__object/parameter/user")"
directory="$(cat "$__object/parameter/directory")/$package"

#install dependencies as root
#echo "source $directory/PKGBUILD && pacman -Sy --noconfirm --needed --asdeps \"${makedepends[@]}\""

#make package as user
echo "su - $user -s /bin/bash -c \"(cd $directory && makepkg -f)\""

#install package as root
echo "pacman --noconfirm -U $directory/*-x86_64.pkg.*"
